### ISSUE TITLE
Waifu motivation events

### ISSUE THREAD

**Issue by zd-zero** [zd-zero/waifu-motivator-plugin#10]
Motivation based on time or events.
For example, when you noticed that you're always slacking around 3 pm, you can set an event every 3 pm for your waifu to motivate you and you can continue coding. Users could also customize these in settings to set the time motivation and pick an asset for that.

Type of events:
* **Time** - for events with a specified time motivation is triggered.
* **Duration** - for events like staying on a file for 1hr, or working on the project for an hour a specified motivation is triggered.

This issue is blocked by #17 as we needed it to set which motivation asset is triggered if an event happened.

**Comment by Unthrottled** [comment]
Is this issue still relevant?

Considering that there are now more events that trigger motivation, do we still need this? 
I already see waifus a bunch now.

**Comment by zd-zero** [comment]
> do we still need this?
I already see waifus a bunch now.

Agree, users will have *Waifu* fatigue, will close this now.
