### ISSUE TITLE
Add images associated to the notification alert

### ISSUE THREAD

**Issue by zd-zero** [zd-zero/waifu-motivator-plugin#100]
This will improve the user experience to instead of just having a text on each notification, it'll be helpful if there's an image or even better a `gif` to display together with the motivation.

**Comment by Unthrottled** [comment]
I was just goofing around and got something like this.
I never knew I wanted something so much.

![Peek 2020-07-16 19-04](https://user-images.githubusercontent.com/15972415/87734109-4e8bdf00-c797-11ea-8810-702cba906042.gif)


It may require having internet though.

**Comment by zd-zero** [comment]
> I was just goofing around and got something like this.

😂 
Now we're talkin'! Would you like this to be included in `WMP v1.2` instead of `WMP v1.2.1` but we needed more assets for this.

**Comment by Unthrottled** [comment]
It might be a good idea just to figure out what gifs/images that we would want to use. I think this feature it currently is technically feasible.

I'll have to look into this some more, because it is using assets not bundled in the plugin.

**Comment by Unthrottled** [comment]
Okay, I figured out how to do it without always needing an internet connection. 

I can elaborate on my thoughts on what I want to do if you want.

**Comment by Unthrottled** [comment]
Oh yeah, if you want me to assign myself to issues, I can't do that at the moment.

**Comment by zd-zero** [comment]
My bad, I'll assign it to you then 😉

**Comment by Unthrottled** [comment]
I really like this feature, so I am going to try my best to keep it small and focused. I could go crazy add a bunch of stuff with this! (This feels like a larger milestone feature to me)

How this for start, I add the depicted gif above to the notification when tests pass? Then take it from there.

**Comment by zd-zero** [comment]
Sure! We can do that, as users can disable this. I'm also planning to add more settings as the notifications may get in the way especially when going for TDD as users will receive more notifs for the fail and pass tests. #106. We can move this issue to Milestone `WMP 1.2` if you want as this feature is cool 🔥

**Comment by Unthrottled** [comment]
> We can move this issue to Milestone WMP 1.2 if you want as this feature is cool 

Whatever works for you. 

I just want Caramelldansen girls to show up when my tests pass :joy:

**Comment by Unthrottled** [comment]
@zd-zero 

One of the things I want to do is to be able to download the visual asset and have it available locally. That way this can be used offline and not always have to worry about having a steady internet connection (without it being in the plugin).

I've solved this problem before, I have set up a global CDN that looks a bit like this:

- https://doki.assets.unthrottled.io/backgrounds/misato_dark.png
- https://doki.assets.unthrottled.io/backgrounds/misato_dark.png.checksum.txt

I have the real asset, then I have the checksum. The checksum is used to determine if the locally installed asset is the same as the remote. If they differ, then I update the asset. I check like once a day to see is an update for an individual asset (the same could be done for these visual assets).

I use the checksum, because I pay for bytes across the wire, and it is cheaper send 32 bytes than always downloading something bigger :joy: .

I can set something up on my end (because I already have the tools/infrastructure), you could set up something on your end, or we could just use something like imgur.com and just always update at some interval.

**Comment by zd-zero** [comment]
Wow! I was actually thinking about this to not increase our plugin size. Initially, I want the plugin to consume an API and store it as a cache so we don't bundle the assets with the plugin (#123), we could go for this one and extend this with the API integration for some time, In future, we can use the API to have users so each user can provide their own assets and personalize it to whatever they want.

> I check like once a day

Do you check on every startup of the project? or is it a CRON job?

**Comment by Unthrottled** [comment]
I'll set it up to check on startup of the project. I'll have it set up to do it at most once a day for each asset.

I'll get something together and we can take it from there.

**Comment by Unthrottled** [comment]
![Peek 2020-07-21 18-48](https://user-images.githubusercontent.com/15972415/88118313-e36d4e80-cb82-11ea-8873-4910e5277572.gif)

Here is what I got so far.

This is not going to be a small PR, however, I am doing my best to keep the changes minimal and on target. I've only really changed how the test pass stuff works. I've got lot's of fun ideas, I just need to keep things focused.

**Comment by zd-zero** [comment]
That's lit 🔥
You never fail to amaze me, for now, let's keep it simple and we'll just extend it from here, let's aim for the low hanging fruit first. 

Also, I would be off for a few days and if you're interested as you've made key features in this project I can invite you as a collaborator as I see that you're more experienced in doing this and I'll be glad to have you. Let's aim to have a waifu-ish theme to developer IDEs with both doki-theme and this plugin installed 😂

**Comment by Unthrottled** [comment]
I'd be happy to help out as a collaborator. I've actually wanted a feature like this for a long time, I was actually stoked that this plugin existed. 

I've spent a lot of time adding adding cute anime girls to things. Is Wafiu Driven Development a thing? (it should be) :joy:  

Anyways no rush, I'll be working on this for a bit.

**Comment by zd-zero** [comment]
This is really a nice feature and now resolved by #126 🎉
