### ISSUE TITLE
Welcome dialog for newly installed plugin or new version

### ISSUE THREAD

**Issue by zd-zero** [zd-zero/waifu-motivator-plugin#102]
This dialog will display the current version and its respective changes.

**Comment by Unthrottled** [comment]
@zd-zero I can help out with this if you want.  Also, how do you feel about Kotlin? We can mingle Kotlin code with Java code if you so choose.

**Comment by zd-zero** [comment]
Woah! 🔥 
I'll be glad for this offer. You can take this, I haven't finished creating proper `CONTRIBUTING` information. This issue has a milestone `WMP v1.2` and it should base from [wmp-1.2](https://github.com/zd-zero/waifu-motivator-plugin/tree/wmp-1.2) branch. Feel free to self-assign this issue and you can use Kotlin, even though I haven't tried it yet, I'll learn something from it 👍 .

Thank you for the interest in contributing @Unthrottled  🙂

**Comment by Unthrottled** [comment]
> I intended to use the recent changes from pluginChanges.html 

Personally, if you give me a wall of text, I'll probably not read it.

What I try to do is summarize the main changes in couple of bullet points and provide a link to a changelog where I can get more details if I want.

Like this:
![image](https://user-images.githubusercontent.com/15972415/87658131-5dd04580-c721-11ea-8054-f2819635b8c5.png)

Thoughts? :thinking:

**Comment by zd-zero** [comment]
> Personally, if you give me a wall of text, I'll probably not read it.

Yes, you're right about that. We'll just go with the summarization of the key changes of the latest version. We can go with that one as it looks clean and simple compared to the dialog with the wall of text. ✨

Related to links, I'm thinking if we could also include the link to the project [Waifu of the Day](https://github.com/zd-zero/waifu-motivator-plugin/projects/3) and [Waifu Assets](https://github.com/zd-zero/waifu-motivator-plugin/projects/2) for them to request additional Waifus and assets, as I'm planning if this gets too big we'll create an API for this and only add few assets so if there's no internet connection, we can still present them their _Waifu_. Would it be okay if we include it to the Welcome dialog? or we could just put this somewhere else?

I'm thinking something like
> If you want your Waifu to be included in this plugin, you can request and add it to  [Waifu of the Day](https://github.com/zd-zero/waifu-motivator-plugin/projects/3) ...

**Comment by Unthrottled** [comment]
How's this for a start?
![image](https://user-images.githubusercontent.com/15972415/87664172-6e38ee00-c72a-11ea-965b-f8b8336d898c.png)

It shows in the  upper-right hand corner. I just put some stuff in the changes at the moment.

Anything you want to remove/add?

**Comment by zd-zero** [comment]
Only a few typos around
> Missing your Wafiu?

I really like how you worded for adding assets and waifu of the day 😉

LGTM 🎉

**Comment by zd-zero** [comment]
Resolved by #113 .
Thank you for your contribution @Unthrottled 🎉 I really appreciate it as I only spend a few mins to work on this. Your contributions will help us to publish the next version sooner as we're hitting 500 downloads 😊
