### ISSUE TITLE
Improve settings descriptions

### ISSUE THREAD

**Issue by zd-zero** [zd-zero/waifu-motivator-plugin#108]
The setting description for checkboxes seems redundant, as the checkbox already indicates that one is enabled when ticked. So we are now implying that when the checkbox is ticked, the setting is enabled. Also, rename `"Actions"` into `General"`.

<img width="384" alt="Screen Shot 2020-07-03 at 3 46 06 AM" src="https://user-images.githubusercontent.com/21978370/86403193-c958f280-bcdf-11ea-93c4-30ef60ac2d03.png">

e.g.
From `✅ Enable Startup notification` to just `✅ Startup Notification` which I think that it conveys the same meaning but more concise.

This will affect the key modifier for `Enable sound on Motivate Me`, we could change this to "S**o**und on Motivate Me" (`o` alt modifier)

**Comment by Unthrottled** [comment]
Resolved by #146
