### ISSUE TITLE
Add Kotlin state support

### ISSUE THREAD

**Issue by Unthrottled** [zd-zero/waifu-motivator-plugin#114]
Ohh, that explains the reason why other parts are changed. Do you think it'll take more effort if we separate the PR for converting the `WaifuMotivatorState` first to Kotlin and make this PR on top of that so that we can have a minimum change to the PR?

_Originally posted by @zd-zero in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1NjE1MDc2Nw==/comments/review_comment_

**Comment by Unthrottled** [comment]
It looks like every PR has an issue tied to it, so I am guessing this is the process of adding stuff :shrug:

**Comment by zd-zero** [comment]
I try to add issue for every not so minor change so if anyone jumps into the project it'll serve as a documentation.

**Comment by zd-zero** [comment]
Resolved by #115
