### ISSUE TITLE
Waifu API Integration

### ISSUE THREAD

**Issue by zd-zero** [zd-zero/waifu-motivator-plugin#123]
Ability to use Waifu APIs and store or cache it locally so the plugin wouldn't get bigger in download size if we add more Waifus. We could create our own API and have an event-like for today to celebrate a Waifu and should sync on all platforms for their first _Waifu of the Day_.

**Comment by Unthrottled** [comment]
The #161 should address the caching of the current assets.

Is this something along the lines of us managing the waifu of the day that is presented to the user? If so, this is a much bigger effort that extends to outside this plugin. It sounds neat though, I would have to think about the offline functionality. It would also move it out of the v1.4 milestone.

**Comment by zd-zero** [comment]
We could move this until we have enough resources so we could compile it and consume it centrally with one API.

**Comment by Unthrottled** [comment]
I think there is consensus on this issue not being necessary. If this is not the case, feel free to re-open the issue.
