### ISSUE TITLE
Build/Compilation Events

### ISSUE THREAD

**Issue by Unthrottled** [zd-zero/waifu-motivator-plugin#133]
~~There are plenty more actions that happen within the IDE that can trigger motivation events.
Some of those can include (but not limited to):~~

~~- [ ] Build/Compilation Failure (and a follow up on the first success after a failure(s))~~

~~- [ ] Program exiting with a non-zero zero code.~~

~~- [ ] VCS Events (push/commit/etc.)~~

~~- [ ] Long duration without interacting with the IDE (eg, thinking hard about a problem)~~

When a program that I build fails to compile then I expect a failure/shocked event.

Given a program build that has failed, the next time a program build successfully then I expect a celebration/smug event.

**Comment by Unthrottled** [comment]
I really like the idea of if the IDE has been out of focus or idle for a period of time, that the plugin should pop-up an alert with a patiently waiting anime girl. Such as (but not limited to)

![Ryuko](https://media1.tenor.com/images/89ad793bba0a210af06bb1742fdf52df/tenor.gif?itemid=123905300)

![oki](https://media1.tenor.com/images/4e8708fe18087afdb2b717b8a06c6c0b/tenor.gif?itemid=13238293)

![So cute](https://media1.tenor.com/images/769944bacab648e4bae9dfebff14016c/tenor.gif?itemid=5525897)

![Kanna](https://media1.tenor.com/images/32a19f23477c9ddcc447a0c0479528f4/tenor.gif?itemid=14379508)

**Comment by zd-zero** [comment]
For "Build/Compilation Failure (and a follow up on the first success after a failure(s))", maybe we could use `com.intellij.openapi.compiler.CompilerTopics` but they suggest to use `com.intellij.task.ProjectTaskListener` instead.

```java
package zd.zero.waifu.motivator.plugin.listeners;

import com.intellij.task.ProjectTaskListener;
import com.intellij.task.ProjectTaskManager;
import org.jetbrains.annotations.NotNull;

public class WaifuCompilationListener implements ProjectTaskListener {

    @Override
    public void finished( @NotNull ProjectTaskManager.Result result ) {
        if ( result.hasErrors() ) System.out.println( "Build Failed!" );
        else System.out.println( "Yay!" );
    }

}
```

and the `plugin.xml`
```xml
  <projectListeners>
    ...
    <listener class="zd.zero.waifu.motivator.plugin.listeners.WaifuCompilationListener"
              topic="com.intellij.task.ProjectTaskListener"/>
  </projectListeners>
```

This works for both Gradle and Maven build tools.
