### ISSUE TITLE
Support publishing a plugin with Gradle

### ISSUE THREAD

**Issue by zd-zero** [zd-zero/waifu-motivator-plugin#141]
Configure the publishing of plugin to different channels with
```
./gradlew publishPlugin
```

This way we can configure it with channels like EAP, Beta, and Stable. We can have somewhat 'nightly builds', and can share the plugin for interested people who wants to try the latest version during development.

Automate the building and publishing of plugins to different channels.

Branches for nightly builds (`wmp-1.x`) should point to either `alpha` or `beta` channels while `development` branch should publish to `eap` channel.

For [reference](https://jetbrains.org/intellij/sdk/docs/tutorials/build_system/deployment.html#publishing-a-plugin).

**Comment by Unthrottled** [comment]
> When using a non-default release channel, users will need to add a new custom plugin repository to install your plugin.

Very cool, looks like an approval from the plugin admins might not be needed when publishing to other channels. Guess I did not need to make my own plugin repository :shrug:
