### ISSUE TITLE
Just your Waifu

### ISSUE THREAD

**Issue by Unthrottled** [zd-zero/waifu-motivator-plugin#174]
As a user, I want to only see my favorite girl.

Expect a way to set all motivation events to only include my waifu.

This could apply to all events or just a specific event (such as Test pass or build passing)

**Comment by zd-zero** [comment]
Nice, in order for us not to forget this should be preceded by #142 so that the event assets are not mixed up by different *Waifu*.

**Comment by Unthrottled** [comment]
Yeah! That's a good idea. It's going to be a lot of scavenger work to find assets that match all the categories AND contain the same waifu!

**Comment by Unthrottled** [comment]
> in order for us not to forget this should be preceded by #142 

I think the solution that was built for #142 can work in tandem with this issue. I think it is just a matter of tagging specific visual assets with what Waifu the image depicts. That way we can choose assets based off of a specific girl(s). 

I feel that this limits the pool of visual assets to the girl(s) the user wants, we just pick an visual asset and gather any grouped assets for that visual asset. That way all the things work together.

That doesn't sound to crazy does it or am I missing a important detail?
