### ISSUE TITLE
Group Event Settings

### ISSUE THREAD

**Issue by zd-zero** [zd-zero/waifu-motivator-plugin#190]
As we have different types of events (currently 3 events: Task, Idle, and Exit Code), should we group them into one tab named "Events" and with different subgroups

<img width="694" alt="Screen Shot 2020-09-09 at 03 52 07" src="https://user-images.githubusercontent.com/21978370/92521565-072e4600-f250-11ea-94cd-5115359c2925.png">

![Note Sep 9, 2020 03_54_46](https://user-images.githubusercontent.com/21978370/92521995-b23eff80-f250-11ea-95da-f6208f466771.png)

**Comment by Unthrottled** [comment]
![Yes](https://media.giphy.com/media/H6Qqxi3RsbyuCry8Ma/giphy.gif)

We should also probably group the unit testing and startup events as well, yes?

**Comment by zd-zero** [comment]
Yep, forgot about those!

**Comment by Unthrottled** [comment]
Resolved by #197
