### ISSUE TITLE
Gender selection option for voice lines.

### ISSUE THREAD

**Issue by ltouroumov** [zd-zero/waifu-motivator-plugin#191]
As a user, I want to have have the ability to filter out voice lines based on gender (masculine, feminine, neutral).

Getting called _Onii-chan_ as a woman feels weird.

**Comment by zd-zero** [comment]
> Getting called Onii-chan as a woman feels weird.

I agree that it feels weird 😅. 

Hmmm, I'm thinking if we consider adding a `husbando` option as this aims `waifu` characters, we still need to default it to waifu voice lines or better yet at the installation phase, there would be an initial option configuration for selecting those, like onboarding configuration. This will open up new stories for hunting voice assets for those voice lines.

This is a good ticket and this also opens up new opportunities or different ideas:
1. We can create a core plugin that would be based/extended by other plugins
  idea-motivation-plugin is the core plugin, and waifu-motivation-plugin, husbando-motivation-plugin, or even cat-motivation-plugin, etc. can extend from the core plugin.
2. Drop the `waifu` term and change it to `anime` motivator, and have it integrated to choose from a variety of assets (waifu, husbando, etc.). 

These options will surely take some time, but for lesser friction, we can just have the option configuration at the installation setup and could be changed anytime at the plugin settings.

@ltouroumov wdyt? If you have any suggestions on how we can approach this please share it 🙇‍♂️
CC: @Unthrottled

**Comment by Unthrottled** [comment]
@zd-zero I get where you are going with your suggestions (which would be good in the future), however I think that isn't necessarily the issue, that was brought up.

I think it's more along the lines of the message to the user and not the message deliverer.

Such as, if I was using it and there was a male voice giving me a message of `That's it! You go girl!`. I wouldn't really bothered by the fact that it is a dude saying it. It's more a long the lines of "Yes did succeed, however,  _I'm not a girl_ bro..."

So I think a simpler (short term) fix would be to have voice messages that address the user be gender agnostic. As I just kept the wav files from the old messages. I am already pretty sure I left gender out of the motivation event titles, yes?

**Comment by ltouroumov** [comment]
> So I think a simpler (short term) fix would be to have voice messages that address the user be gender agnostic. As I just kept the wav files from the old messages. 

I think there's only one voice line that is gendered.

´´´
{
  "title": "Awww",
  "message": "Ganbatte Onii-chan!",
  "sound": "ganbatte_onii_chan.wav",
  "categories": [
    "negative"
  ]
}
´´´

**Comment by Unthrottled** [comment]
Cool! I forgot that `v1.2` still has the audio and text assets still bundled in the plugin. With `v1.3` we are able to control the assets that are shown to the user at runtime. I'll have it removed from the current list of usable assets. Changes will take effect when `v1.3` is publicly available, which should be either this weekend or early next week. Sound fair @ltouroumov ?

Just as a FYI @zd-zero, I blacklisted `ganbatte_onii_chan.wav` from https://waifu.assets.unthrottled.io/audible/assets.json for the time being.

**Comment by zd-zero** [comment]
> @zd-zero I get where you are going with your suggestions (which would be good in the future), however I think that isn't necessarily the issue, that was brought up.

Yep, I just can't help myself to share any ideas that popped up 😅.

> we can just have the option configuration at the installation setup and could be changed anytime at the plugin settings.

So in here, I did suggest if we have more voice lines with gender-specific we can do this, turns out that there's only one: `ganbatte_onii_chan.wav`.

> Just as a FYI @zd-zero, I blacklisted ganbatte_onii_chan.wav from https://waifu.assets.unthrottled.io/audible/assets.json for the time being.

Noice! And grateful that it's now removed from the list.

Moving forward, @ltouroumov have we addressed your issue? As @Unthrottled decoupled the assets away from the plugin so we can dynamically update the list and reduce the plugin size, this will come with the `v1.3` release.

**Comment by ltouroumov** [comment]
> Moving forward, @ltouroumov have we addressed your issue?

Yup 😄 

(sorry for the late reply, I was in holidays)
