### ISSUE TITLE
Update CHANGELOG documentation

### ISSUE THREAD

**Issue by zd-zero** [zd-zero/waifu-motivator-plugin#220]
This issue helps to make the [CHANGELOG](https://github.com/zd-zero/waifu-motivator-plugin/blob/master/docs/CHANGELOG.md) content to be consistent.

- [x] Update links to point to [release tags](https://github.com/zd-zero/waifu-motivator-plugin/releases) of the respective versions
- [x] Update date to H4
- [ ] Add emojis to other titles
 - ✨ for features
 - 🐛 for bugfix
 - ❤️ for contributors
- [ ] Make the 'Waifu of the Day' and 'Alert Assets' section of WMP v1.1 collapsable 

This is relevant to the current and future versions, so the PR's target branch should point to `master` branch.

**Comment by diamondlee7** [comment]
@zd-zero  I would like to fix this issue. Can you please assign it to me?

**Comment by zd-zero** [comment]
Hi @diamondlee7, I've assigned the issue to you 💪
