### ISSUE TITLE
Upgrade Linter

### ISSUE THREAD

**Issue by Unthrottled** [zd-zero/waifu-motivator-plugin#234]
This project currently uses Kotlin 1.4.0 which has a bunch [of cool features](https://kotlinlang.org/docs/reference/whatsnew14.html)

However, the current version of the Kotlin linter does not recognize the features. 
Time to upgrade!

**Comment by Unthrottled** [comment]
To reduce merge-conflicts, let's coordinate on when to submit the PR. 

Upgrading might cause new styling/formatting to occur.

**Comment by zd-zero** [comment]
> Upgrading might cause new styling/formatting to occur.

I see it should be included in the PR for the styling/formatting issues when we bump the linter.

> To reduce merge-conflicts, let's coordinate on when to submit the PR.

I think that it would be best to add this earlier so the future PRs would contain the latest features of Kt.
