### ISSUE TITLE
Relax, it's not that big of a deal.

### ISSUE THREAD

**Issue by Unthrottled** [zd-zero/waifu-motivator-plugin#235]
- [X] I'd be willing to implement this feature

**Describe the user story**

As somebody who is having a hard time coding, when I have sequentially triggered many negative events and have frustrated my companion even though I'm not frustrated then I expect a way to tell my companion to "Relax". 

**Describe the solution you'd like**

I'd like to be able to invoke an action and have my companion not be frustrated anymore.
Bonus points if I get a visual representation of my companion's acknowledgment, 

e.g. 
![Command Authenticated](https://media.tenor.com/images/4e4aca6054a37384ac0beb7f3937cb01/tenor.gif)

**Comment by Unthrottled** [comment]
Do you think it would be helpful to display the mood to the user?

**Comment by zd-zero** [comment]
> Do you think it would be helpful to display the mood to the user?

Hmmm, I think that it would be helpful to display it, as when the user invoked the action and no feedback happens, it would seem that the action didn't work and there's no way to verify it if there's nothing shown from the user point of view.
