### ISSUE TITLE
Plugin Installation Error

### ISSUE THREAD

**Issue by Unthrottled** [zd-zero/waifu-motivator-plugin#242]
## Issue Context 
I installed the plugin through the Doki-Theme motivator plugin promotion, and it made a big sad during installation.

Relevant stack trace:
https://sentry.io/share/issue/a38cb0f1deac4b959182cd3309e3cb92/

#### Supporting information

Additional Info | None
-- | --
App Name | IntelliJ IDEA 2020.2.3 (Community Edition)
Build Info | Build #IC-202.7660.26, built on October 6, 2020
Cores | 8
Current LAF | KillLaKill: Ryuko
GC | ParNew,ConcurrentMarkSweep
JRE | Runtime version: 11.0.8+10-b944.34 x86_64
Memory | 1981
Message | Error executing task zd.zero.waifu.motivator.plugin.WaifuMotivatorProject$$Lambda$4073/0x00000008028f1c40@7dc98663
Non-Bundled Plugins | Lombook Plugin,com.markskelton.one-dark-theme,io.acari.DDLCTheme,io.acari.normandy.progress.bar,io.unthrottled.themed-components,org.jetbrains.kotlin,zd.zero.waifu-motivator-plugin
Plugin Config | {   "isWaifuOfTheDayEnabled": false,   "isStartupMotivationEnabled": true,   "isStartupMotivationSoundEnabled": true,   "isUnitTesterMotivationEnabled": true,   "isUnitTesterMotivationSoundEnabled": true,   "isMotivateMeEnabled": true,   "isMotivateMeSoundEnabled": true,   "isSayonaraEnabled": true,   "isDisabledInDistractionFreeMode": true,   "isTaskMotivationEnabled": true,   "isTaskSoundEnab...
Registry | ide.intellij.laf.enable.animation=true,bigger.font.in.project.view=true,ide.balloon.shadow.size=0
System Info | macOS 10.15.5
VM | VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by zd-zero** [comment]
I can't seem to reproduce this issue.
My steps are:
* Clone and run the doki-theme locally
* Trigger to show promotion dialog
* Install WMP plugin from promotion

Can't see any stacktrace.

**Comment by Unthrottled** [comment]
I don't exactly remember the exact steps. I think I might have closed the project before loading :shrug: 

However, we can fix the symptoms of the issue, so that it doesn't magically happen again.

**Comment by zd-zero** [comment]
I also noticed on the first install of the plugin, it triggers Sayonara 😂, it's the filed #241 right?

**Comment by Unthrottled** [comment]
Yeah, it scared me when I did ran the install from the promotion. Was not expecting a loud `SAYONARA BYE-BYE!!!` :smile:
