### ISSUE TITLE
Incompatible with IntelliJ IDEA 2021.1

### ISSUE THREAD

**Issue by dimonchik0036** [zd-zero/waifu-motivator-plugin#248]
<img width="408" alt="изображение" src="https://user-images.githubusercontent.com/22503910/96829585-2aa9fa80-1464-11eb-8b62-a23fac0355a9.png">

**Comment by zd-zero** [comment]
Hmmm, can you provide more info, what's the version and build number so I can try to reproduce it on my end?
At the moment, we're supporting this build version range

https://github.com/zd-zero/waifu-motivator-plugin/blob/8e0343fd261aadff283e7fc2782f62cf7a5a1a18/gradle.properties#L2-L3

If you can provide the platform information from the `About IntelliJ IDEA` dialog, it would really help us to deal with this issue and move forward.

I'm assuming that it is a typo and the filed issue pertains to `2020.1`, I'll go ahead and update it.

**Comment by dimonchik0036** [comment]
IntelliJ IDEA 2021.1 Snapshot (Ultimate Edition)
Build #IU-211.102, built on October 22, 2020

**Comment by dimonchik0036** [comment]
Replacing `untilBuildVersion=203.*` with `untilBuildVersion=211.*` should be enough. The plugin works if I locally patch the version in the plugin jar

**Comment by Unthrottled** [comment]
@dimonchik0036 Any Ideas on how we could, conveniently,  get our hands on the 2021.1 builds for plugin development? That way we can verify things work as expected.

**Comment by dimonchik0036** [comment]
As far as I know, you can only build manually from the [sources](https://github.com/JetBrains/intellij-community) and then replace the build [property](https://github.com/JetBrains/gradle-intellij-plugin#intellij-platform-properties) `intellij.version` with `intellij.localPath`.

**Comment by zd-zero** [comment]
Whoops, I was checking the public snapshots and found no `2021.x` so I assumed it was `2020.x` 😅. I'll try changing it to `untilBuildVersion=211.*` later and see if it'll work on my local. If it works, then I'll include it in [canary v1.3.1](https://github.com/zd-zero/waifu-motivator-plugin/tree/canary/v1.3.1).

**Comment by zd-zero** [comment]
Can't seem to find the branch for `2020.1`, the `master` branch still builds for `2020.3` so what I did instead was to publish it to the canary channel, and it should be publicly available within 2 business days. But you can already download the package [here.](https://plugins.jetbrains.com/plugin/13381-waifu-motivator/versions/canary/100411)

Please advise if it's already compatible with `2021.1` so we can put the changes to the base branch.

**Comment by dimonchik0036** [comment]
Thanks! It works.
PS: the `master` is based on 211 (`2021.1`) (e.g. https://github.com/JetBrains/intellij-community/commit/9469083d0c8a4e23794a4271b565a53921a2cdcb)
