### ISSUE TITLE
Update waifu of the day image with better quality

### ISSUE THREAD

**Issue by zd-zero** [zd-zero/waifu-motivator-plugin#93]
Update the existing images to improve the quality of dark-themed IDEs. Waifu edges are not smooth or contain white spots.
List of images to be updated:

- [x] [ichika_nakano.png](https://github.com/zd-zero/waifu-motivator-plugin/blob/master/src/main/resources/waifu_of_the_day/images/ichika_nakano.png)
- [x] [kotoko_iwanaga.png](https://github.com/zd-zero/waifu-motivator-plugin/blob/master/src/main/resources/waifu_of_the_day/images/kotoko_iwanaga.png)
- [x] [mayuri_shiina.png](https://github.com/zd-zero/waifu-motivator-plugin/blob/master/src/main/resources/waifu_of_the_day/images/mayuri_shiina.png)
- [x] [miku_nakanano.png](https://github.com/zd-zero/waifu-motivator-plugin/blob/master/src/main/resources/waifu_of_the_day/images/miku_nakanano.png)
- [x] [nao_tomori.png](https://github.com/zd-zero/waifu-motivator-plugin/blob/master/src/main/resources/waifu_of_the_day/images/nao_tomori.png)

e.g.
<img width="602" alt="Screen Shot 2020-07-18 at 08 22 00" src="https://user-images.githubusercontent.com/21978370/87839999-015f5880-c8d0-11ea-92ff-6df0cb530647.png">

**Comment by Unthrottled** [comment]
Resolved by #134
